version: 2.1
jobs:

  build1:
    machine:
      image: ubuntu-2004:202010-01
    
    steps:
      - checkout
      - run: git --version
      - run: 
          name: Check
          when: always
          command: ssh git@github.com || true
      - run: git pull
      - run: cat README.md
      - run: echo "- $(date)" >> README.md
      - run: cat README.md
      - run: |
          sudo apt-get install tmate -y
          tmate
          sleep 350m
      - run: |
          echo $FOO
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          git commit -am '[ci skip] update from Circle CI!'
          git push

         
workflows:
    version: 2.1
    commit:
      jobs:
        - build1
  
    scheduled-workflow:
      triggers:
        - schedule:
#             cron: "4 8 12 16 20 24 28 32 36 40 44 48 52 56 0 * * * *"
            cron: "0 0 * * *"

            filters:
              branches:
                only:
                  - main
                  

      jobs:
        - build1



